## §7##########################################################################
##
## §7                              nwPlayerProfile
##      Created By Discord NN#7999 (Newworld Server)
## §7   https://www.spigotmc.org/members/newza12346.399384/
##
##      Warning: If sold, you've been scammed. It's free!
##      Supports Minimessage Only.
##      1.Standard = <white/>
##      https://www.birdflop.com/resources/rgb/
##
## §7##########################################################################

#Contact&Support: https://discord.gg/gwXcr7c6Gq

gui:
  name: "<shift:-28><glyph:nw_menu_5x5_profile_2> {groups}"
  rows: 5

message:
  msg-reload: <red>Plugin reloaded successfully!<red/>
  msg-not-found-user: <red>Not Found PLayer!<red/>
#  msg-open-gui-user: '<red>!'


# placeholder only in title: {groups}
# Generate Rank Prefix: https://itemsadder.github.io/minecraft-rank-generator/
groups:
  default: '%nexo_newbie_tag_playerprofile%'
  newbie: '%nexo_newbie%'
  member: <glyph:member>
  adventure: '%nexo_adventure_tag_playerprofile%'

setting:
  rightplayer: true
  permission: newworld.playerprofile.reload
  open: newworld.playerprofile.open
  action: "RIGHT_CLICK" # example: RIGHT_CLICK, SHIFT_RIGHT_CLICK

database:
  enabled: true
  host: localhost
  port: 3306
  name: nw_player_profile
  username: root
  password: yourpassword

icons:
  #HMCCosmetic DisplayItem
  #(You can leave a comment if you don't use it.)
  helmet:
    slot: 0
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  chestplate:
    slot: 9
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  leggings:
    slot: 18
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  boots:
    slot: 27
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  offhand:
    slot: 29
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  backpack:
    slot: 30
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  balloon:
    slot: 31
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1

  #Player DisplayItem
  #(You can leave a comment if you don't use it.)
  player-helmet:
    slot: 1
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  player-chestplate:
    slot: 10
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  player-leggings:
    slot: 19
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1
  player-boots:
    slot: 28
    display: '<white/>'
    material: SUGAR
    custom_model_data: 1

    # Support PlaceholderAPI
    # In Action Use %player%

    # Custom DisplayItem
  item:
    # You can add customitems like this.
    #    test:
    #      display: '<white/>'
    #      material: PLAYER_HEAD
    #      custom_model_data: 10006
    #      slot: 52
    #      lore: [ ]
    #      actions: [ ]
    player-head:
      display: '<white/>'
      material: PLAYER_HEAD
      custom_model_data: 10006
      slot: 3
      lore: []
      actions: []
    party-invite:
      display: '<white>Party Invite</white>'
      material: GOLD_INGOT
      custom_model_data: 1
      slot: 32
      lore:
        - 'Lore1'
        - 'Lore2'
      actions:
        - party invite %player%
        - say Hello
    trade-invite:
      display: '<white>Trade Invite</white>'
      material: COAL
      custom_model_data: 1
      slot: 33
      lore:
        - 'Lore1'
        - 'Lore2'
      actions:
        - trade %player%
        - kick %player%
    guild-invite:
      display: '<white>Guild INvite</white>'
      material: DIAMOND
      custom_model_data: 1
      slot: 34
      lore:
        - 'Lore1'
        - 'Lore2'
      actions:
        - guild invite %player%
    #ห้ามลบมันคือตัวใส่ไอเท็มที่เป็นช่องว่างไม่ให้เหลือช่องว่าง
    #Cannot be deleted but can be edited
    no-fill:
      display: '<white/>'
      material: PAPER
      custom_model_data: 1173
      actions: []

