name: nwPlayerProfile
version: '1.4.6-FREE'
main: com.nwPlayerProfile.NwPlayerProfile
api-version: '1.21'
load: STARTUP
description: nwPlayerProfile
author: Discord NN#7999
depend: [ HMCCosmetics ]
softdepend:
  - Nexo
  - ItemsAdder
  - luckPerms
  - Placeholders
  - Citizens
commands:
  nwPlayerProfile:
    description: Base command for NwPlayerProfile.
    usage: /nwPlayerProfile <reload>
    aliases: [ nwpp,profile ]